[world]
name = "Dojo starter"
description = "The official Dojo Starter guide, the quickest and most streamlined way to get your Dojo Autonomous World up and running. This guide will assist you with the initial setup, from cloning the repository to deploying your world."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "dojo_starter"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "dojo_starter"

[env]
rpc_url = "https://api.cartridge.gg/x/tenpercentfun/katana"
katana_slot_command = "slot deployments logs tenpercentfun katana -f"
katana_deploy_command = "slot deployments create tenpercentfun katana"

torii_url = "https://api.cartridge.gg/x/tenpercentfun/torii"
torii_slot_command = "slot deployments logs tenpercentfun torii -f"
torii_deploy_command = "slot deployments create tenpercentfun torii -w 0x065ee8188c171a836294feaa931f1c78b5f18957791c039e84ee40b4b3e85d3e --rpc https://api.cartridge.gg/x/tenpercentfun/katana"

account_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"
#world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7" # Uncomment and update this line with your world address.

[writers]
"dojo_starter" = ["dojo_starter-actions"]
