[package]
cairo-version = "=2.9.2"
name = "dojo_starter"
version = "1.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo clean && sozo build && sozo migrate"                      # scarb run migrate

# join game
jp1 = "sozo execute actions join_game 0"
jp2 = "sozo execute actions join_game 0 --account-address 0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7 --private-key 0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"
jp3 = "sozo execute actions join_game 0 --account-address 0x17cc6ca902ed4e8baa8463a7009ff18cc294fa85a94b4ce6ac30a9ebd6057c7 --private-key 0x14d6672dcb4b77ca36a887e9a11cd9d637d5012468175829e9c6e770c61642"
jp4 = "sozo execute actions join_game 0 --account-address 0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba --private-key 0x1800000000300000180000000000030000000000003006001800006600"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.9.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }
